### ISSUE TITLE
Difference between this an rekapi-timeline?

### ISSUE THREAD

**Issue by trusktr** [jeremyckahn/mantra#7]
Hello! Nice projects! 

There's two repos (mantra and rekapi-timeline), whose landing pages look almost the same. What's the difference?

**Comment by jeremyckahn** [comment]
Hi @trusktr, thank you for the compliment! rekapi-timeline is a component of Mantra. It's a separate repo so that it can be imported into any other project without all of the non-timeline UI and features of Mantra.

Mantra is meant to be an end-to-end animation solution with designers in mind. It provides a variety of utilities to modify animations visually and then export them to CSS. rekapi-timeline is more of a tool for developers to integrate into their own projects. Hopefully that makes sense! 😄
